### ISSUE TITLE
Server crashes randomly

### ISSUE THREAD

**Issue by AStopher** [AStopher/Wildfire-Public#2]
Randomly the server will crash with a StackOverflowException.
Can happen anywhere from a couple of hours to a couple of weeks.

**Comment by AStopher** [comment]
Issue has yet to be identified but the server is being debugged remotely so I should know exactly what's causing this when it crashes next time.
The system may be unavailable for a short period after any crashes- if it is not put back up within five minutes please message me on Skype so I can put it back up again.

I should be able to get enough debug info from just one crash to fix the issue, but will update this if anything else happens.

**Comment by AndrijaaKolesarr** [comment]
Hi, I have such a question why yesterday evening the wildfire system was working this morning broke out what is going on you have some ideas that would keep it running and not how it gets up the system fell

**Comment by AStopher** [comment]
> Hi, I have such a question why yesterday evening the wildfire system was working this morning broke out what is going on you have some ideas that would keep it running and not how it gets up the system fell

It keeps crashing unfortunately, I'm currently exploring the option of running the system as a service- this'll mean that the Windows Task Scheduler monitors the system and restarts it if it crashes.

**Comment by AndrijaaKolesarr** [comment]
ah, you can fix it or not very once you were fine also 4 5 months ago?

**Comment by AndrijaaKolesarr** [comment]
You can fix it or not .. once it was fine Wildfire system?

**Comment by AndrijaaKolesarr** [comment]
You will have to update your Wildfire system and the site will show me the request on the main page and it seems to be suspended in the same way the server does not show.

**Comment by AStopher** [comment]
I've tracked the issue down to a malfunctioning loop within the code, possibly the code that tracks servers. This code was originally within an entirely separate program but I merged the two projects around March/April 2017 which is around the time this problem started.

My proposed solution is to therefore put this code inside its own executable again. I plan on doing this today and will monitor the system for problems. This will be completed within the standard maintenance window of 11pm-2am GMT.

Meanwhile I've configured the Core executable within the Windows Task Scheduler so Windows monitors Wildfire Core and automatically kills it and restarts it if it crashes. Currently I also have it restarting the system every day at 6am GMT but I plan to reconfigure this to once every 21 days once I have verified that the crashing problem is fixed.

**Comment by AStopher** [comment]
The fix has now been deployed and Epiphany is now running inside its own service.

**Comment by AndrijaaKolesarr** [comment]
But what happened again with the system that today did not work??

**Comment by AndrijaaKolesarr** [comment]
Hello, I do not know why you shut down the system because I would like to play and I do not know how to make my own hosts file I think that hardly and I wanted to play with my friends?
